app_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from portfolio import views as viewsP


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', viewsP.home, name='home'),
    path('blog/', include("blog.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import render_posts, post_detail

app_name = 'blog' #Necesario para comunicar el template con la URL 

urlpatterns = [
    path('',render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail')
]

blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(timezone.now())

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=150)
    image = ImageField(upload_to='portfolio/images')
    url = URLField(blank=True)

    def __str__(self):
        return self.title
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request,'post.html',{'posts': posts})

def post_detail(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    return render(request, 'post_detail.html',{'post':post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request,'home.html',{'projects': projects})

blog/templates/post.html
{% extends 'layout.html' %}
{% block content %}
    <h1> Posts </h1>
    {%for post in posts %}
        <h2>{{post.title}}</h2>
        <p>{{post.date|date:'M d Y'}}</p> 
        <p>{{post.description|striptags| truncatechars:100}}</p>
        <img src="{{post.image.url}}" alt="{{post.title}}" class="img-post">
        <br>
        <a href="{% url 'blog:post_detail' post.id%} ">Leer mas...</a>
        <br>
        <hr>
        
    {% endfor %}

{% endblock content %}

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}
    <h1> Posts Detail </h1>

    <p>{{post.title}}</p>
    <p>{{post.date}}</p>
    <p>{{post.description|safe}}</p>
    <img src="{{post.image.url}}" alt="{{post.title}}"> 
{% endblock content %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}
<header class="row">
    <div class="col-md-4">
        <img src="{% static 'portfolio/profile.png' %}" class="profile-img" alt="">
    </div>
    
    <div class="col-md-8 my-auto" >
        <h1>I am <strong>Leonardo Suarez</strong></h1>
        <h3>I am a Python Backend Developer</h3>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores architecto deserunt nemo itaque, eius iure tempora veritatis velit expedita esse asperiores temporibus accusamus voluptatibus! Aliquam qui minus quia commodi vitae harum modi odit voluptate optio, quidem id iusto suscipit eligendi sunt obcaecati perferendis beatae ratione itaque dolore vero, exercitationem eius temporibus assumenda autem? Laudantium ratione eligendi pariatur ipsam rerum repellendus perferendis quas illo ipsum. Perferendis doloremque quod molestiae omnis autem odit architecto quisquam repudiandae. Amet dolore consequatur soluta cumque quos magni, eius fugit molestias quasi voluptatibus distinctio ullam, vero, architecto veniam praesentium est iste! Quae mollitia expedita libero quos doloremque laboriosam tempore maxime nemo eaque, voluptas quia culpa similique sit repellendus sint delectus in harum aperiam neque perspiciatis autem? Impedit optio quam quaerat, maiores quo aperiam pariatur ipsa beatae ea esse voluptates, temporibus quisquam illum fugit facilis maxime a, odio vitae ab! Accusamus esse provident dolore ab labore repellendus reprehenderit cumque aliquam magnam voluptas. Esse laudantium mollitia dolor incidunt, qui sunt voluptatibus, eum expedita iusto modi ratione autem nemo ut. Temporibus veritatis quos perferendis in quasi quis iusto distinctio, ea beatae et sed natus molestias, hic voluptate ipsam enim corrupti sint fugit omnis sequi ut illo eos! Non, labore ipsum.</p>
        <a href="{%static 'portfolio/Profile.pdf' %}" 
        class="btn btn-primary btn-lg rounded-0 my-3" target="_blank">Download CV</a>
    </div>
</header>

<div class="row my-4 text-center">

    <h3>My Projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla, deserunt?</p>


    {%for project in projects %}
    
    <div class="col-md-4 p-4">
        <div class="card bg-black card-project h-100">
          <img src="{{project.image.url }}" class="card-img-top img-portfolio" />
            <div class="card-body text-light">
                <h2>{{project.title}}</h2>
                <p>{{project.description}}</p>
                {%if project.url %}
                    <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm align-bottom" target="_blank">{{project.url}}</a>
                {%endif%}
            </div>
        </div>
    </div>
    
    {% endfor %}

{% endblock  %}
</div>

portfolio/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="bg-black text-light">
    {% include 'partials/navbar.html' %}
<hr>
<div class="container p-4">
    {% block content %}
    {% endblock %}
</div>


</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">J.Leonardo Suarez</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/Profile.pdf' %}" target="_blank">Download CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>